### ISSUE TITLE
Bonaire

### ISSUE THREAD

**Issue by methanoid** [emeric254/PyHawaiiBiosReader#13]
I know you forked this to add Bonaire support but DID you? And there are no downloads? ReadMe might need update

I'd like to try this on W4300 FirePro BIOS
[FirePro_W4300.zip](https://github.com/emeric254/PyHawaiiBiosReader/files/13684911/FirePro_W4300.zip)

**Comment by emeric254** [comment]
Hello,
You are right the README.md should contains a bit more information.
Download this repo and from Linux (all the major distributions) you only need to execute `python main.py`.

For context I used it successfully few years back to flash my r7 260 (this one https://www.techpowerup.com/gpu-specs/asus-r7-260-1-gb.b2732)
and got it maxed out at something ridiculous like + 250Mhz on the gpu and got around + 500mhz on the ram (to get 8000 effective) ... easy to overclock as the gpu itself is so small (and good luck on the silicon lottery)

what can be edited vary from bios to bios . If you got a "stock PCB" card you can grab  almost any other manufacturer bios that use the same board.  That's what i did with a couple of 290 and 390x.

Both use the same Hawaii bios file https://github.com/emeric254/PyHawaiiBiosReader/blob/master/tools/HawaiiBios.py   simply add you dev id.  As I never tested on a firepro, i'm pretty sure your dev id is not there.

If anything back happen most card can be easily flashed back using a cheap CH341A programmer using the little sop8/soc8 clips.

**Comment by methanoid** [comment]
Thanks I do have a CH341A but foudn the clip was not good to try to attach to BIOS on my previous W4100 but luckily I recovered that anyway

Back to the W4300, https://www.reddit.com/r/overclocking/comments/fmg5n5/i_vbiosmodded_my_firepro_w4300_into_basically_a/?rdt=53520
shows that the Reader works with W4300 (Bonaire)

My card is Stock 930/1500 but I notice it doesn't ever hit 930 (seems to stop at 738) cos it's TDP limited. Confirmed by adding 20% to TDP (35 to 42W) with Afterburner and then clocks hit 850.

So I need a BIOS mod but after reading 47 pages of the thread I was pointed at I didn't find any help in HOW to use the Reader (original or fork).

I'd like to have BIOS set to Core/Mem 1000/1750 (mem checked works at that speed) but what to change for Power Limit?
TDP Max or PowerLimit or Both from 35W to 55W, not sure which I change? Similarly TDC Limit? Surely if TDP goes up must increase TDC current? Power=Current X Voltage after all and voltage isn't changing.

Does GPU or Mem Freq table need adjusting? No idea how!

Would like two Roms to try, one with no voltage tweaks and one with voltages increased, as previous experience modding W5000 and W4300 has shown that increasing voltage isnt possible. They seem to be hardware limited to 1V but perhaps different on W4300 GCN2 card? So don't want to change everything in one go as if it doesn't work then won't know why!

[Bonaire.zip](https://github.com/emeric254/PyHawaiiBiosReader/files/13696479/Bonaire.zip) attached just in case anyone who KNOWS how reader works care's to help and do me sample mods that I can then adjust later? ;-)

Thanks guys :-)

**Comment by emeric254** [comment]
patch https://github.com/emeric254/PyHawaiiBiosReader/blob/master/tools/HawaiiBios.py#L733
to always return true if you feel adventurous and you don't know your device id.

then modify the various tables as you wish 

for example i can bump your rom to 70w tdp max (the one in the software sliders) and the base tdp limit to 50w
![Capture d’écran du 2023-12-18 16-21-03](https://github.com/emeric254/PyHawaiiBiosReader/assets/6140607/5bfa5455-dfb2-40b1-9d29-a0bcdc29a90e)
I also increased your TDC limit to 35A instead of 30A in case it's limiting

once save, the rom you given will be be modified into this one
[Bonaire-modded.zip](https://github.com/emeric254/PyHawaiiBiosReader/files/13705488/Bonaire-modded.zip)


check the card sensors (temps, voltage  etc...) to see if that change anything or not, as their might be other limiting factors. Playing with afterburner should give you a good direction of what to modify :+1:

**Comment by emeric254** [comment]
here is a second bios with more aggressive values. I'm not confident that the card can handle that much without crashing, or they might really slown-down artificially because business :D

![Capture d’écran du 2023-12-18 16-31-16](https://github.com/emeric254/PyHawaiiBiosReader/assets/6140607/4dc47339-2808-4b3b-8e5f-a1ae84df90ec)
![Capture d’écran du 2023-12-18 16-29-50](https://github.com/emeric254/PyHawaiiBiosReader/assets/6140607/75ee57b4-33e4-4b97-ac89-45684c9ba111)

[Bonaire-modd-2.zip](https://github.com/emeric254/PyHawaiiBiosReader/files/13705553/Bonaire-modd-2.zip)

**Comment by methanoid** [comment]
Thanks, I had an experiment this morning and got it working and optimized.  I first unlocked the TDP (70W for both) and the TDC 60A (after all Power=Volts X Amps so 70 = 60 X 1.15 near enough). This allowed it to run at the 930 without downclocking which stock BIOS does. But it got warm so I repasted and temps dropped 10C. I then experimented with increasing the clocks with Afterburner and then modding and decreasing the voltages at each clock and settled on 1000 core but undervolted a fair bit as its a small cooler.

Now the card has identical performance to R7 260 but with 4Gb Ram and temps max out at 87C after long benchmark runs. Performance in Heaven benchmark is 71% better in Avg FPS, Minimums too. Fully DX12 compatible and can be spoofed to be MacOS compatible.  Now a great little card for me for virtualisation passthrough :-)
